---
- name: Install Git
  hosts: vm
  become: yes

  tasks:
    - name: Include OS-specific Git installation tasks
      include_tasks: roles/git/tasks/main.yml
  meta: include_vars roles/git/meta/main.yml
  vars: include_vars roles/git/vars/main.yml
